# Generated by Django 3.0.2 on 2020-01-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logotype', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='DetailOptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption_spr_id', models.IntegerField()),
                ('detail_option_spr_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('icon', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'detail_options',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partcode_id', models.IntegerField()),
                ('model_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
                ('spr_detail_id', models.IntegerField()),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='FilterSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=255)),
                ('subcaption', models.CharField(max_length=255)),
                ('sub_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('values', models.TextField()),
                ('caption_en', models.CharField(max_length=255)),
                ('subcaption_en', models.CharField(max_length=255)),
                ('main_filter', models.IntegerField()),
            ],
            options={
                'db_table': 'filter_settings',
            },
        ),
        migrations.CreateModel(
            name='LinkDetailsOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.IntegerField()),
                ('detail_option_id', models.IntegerField()),
                ('spr_details_id', models.IntegerField()),
            ],
            options={
                'db_table': 'link_details_options',
            },
        ),
        migrations.CreateModel(
            name='LinkModelModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
            ],
            options={
                'db_table': 'link_model_modules',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField()),
                ('scheme_picture', models.TextField()),
                ('picture', models.TextField()),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1500)),
                ('scheme_picture', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Partcodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': 'partcodes',
            },
        ),
        migrations.CreateModel(
            name='Spr_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_ru', models.TextField()),
                ('desc', models.TextField()),
                ('seo', models.TextField()),
                ('base_img', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': 'spr_details',
            },
        ),
        migrations.CreateModel(
            name='SprDetailOptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spr_detail_options',
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('analogs', models.TextField()),
                ('techs', models.TextField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_model.Brands')),
            ],
            options={
                'db_table': 'cartridge',
            },
        ),
    ]
