# Generated by Django 3.0.6 on 2020-08-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgePrice',
            fields=[
                ('cartridge', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db_model.Cartridge')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cartridge_price',
                'managed': False,
            },
        ),
    ]
