# Generated by Django 3.1.6 on 2021-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0003_auto_20200911_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'dictionary_error_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryErrorCodeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'dictionary_error_code_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryModelOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'dictionary_model_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryModuleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'dictionary_module_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryModules',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dictionary_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryPartcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(blank=True, null=True, unique=True)),
                ('name_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dictionary_partcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryPartcodeOptions',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('text_en', models.CharField(max_length=255, unique=True)),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dictionary_partcode_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('display', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('description_id', models.IntegerField(blank=True, null=True)),
                ('causes_id', models.IntegerField(blank=True, null=True)),
                ('remedy_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'error_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkDictionaryModelOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_model_caption_id', models.SmallIntegerField()),
                ('dictionary_model_option_id', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_dictionary_model_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkDictionaryPartcodeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_partcode_caption_id', models.SmallIntegerField()),
                ('dictionary_partcode_option_id', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_dictionary_partcode_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkModelModulePartcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'link_model_module_partcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkModelOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('link_dictionary_model_options_id', models.IntegerField()),
            ],
            options={
                'db_table': 'link_model_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkPartcodeModelAnalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('partcode_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_partcode_model_analogue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkPartcodeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partcode_option_id', models.IntegerField()),
                ('partcode_dictionary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_partcode_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_status', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthAssignment',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthItem',
        ),
        migrations.DeleteModel(
            name='AuthItemChild',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthRule',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='BrandModels',
        ),
        migrations.DeleteModel(
            name='CartridgeAnalogModel',
        ),
        migrations.RemoveField(
            model_name='cartridgeprice',
            name='supplies',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='DetailOptions',
        ),
        migrations.RemoveField(
            model_name='detailprice',
            name='partcode',
        ),
        migrations.DeleteModel(
            name='DetailStatistics',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='ErrorCode',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='LinkCartridgeAnalog',
        ),
        migrations.DeleteModel(
            name='LinkCartridgeModelAnalog',
        ),
        migrations.DeleteModel(
            name='LinkCartridgeOptions',
        ),
        migrations.DeleteModel(
            name='LinkDetailsOptions',
        ),
        migrations.DeleteModel(
            name='LinkModelCartridge',
        ),
        migrations.DeleteModel(
            name='LinkPartcodeModelAnalogs',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Migration',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='PagesSeo',
        ),
        migrations.DeleteModel(
            name='PayHistory',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SellerHasDetails',
        ),
        migrations.DeleteModel(
            name='SellerOffices',
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='SprCartridgeOptions',
        ),
        migrations.DeleteModel(
            name='SprDetailOptions',
        ),
        migrations.DeleteModel(
            name='SprDetails',
        ),
        migrations.DeleteModel(
            name='SprErrorCode',
        ),
        migrations.DeleteModel(
            name='SprErrorCodeImage',
        ),
        migrations.DeleteModel(
            name='SprModuleImage',
        ),
        migrations.DeleteModel(
            name='SprModules',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Cartridge',
        ),
        migrations.DeleteModel(
            name='CartridgePrice',
        ),
        migrations.DeleteModel(
            name='DetailPrice',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
